### ISSUE TITLE
Circular import in bayesian evidence code

### ISSUE THREAD

**Issue by marberi** [PAU-survey/bcnz#15]
Running the default configuration results in:

(bcnz) [eriksen@tdg001 bin]$ ./run_bcnz.py /data/astro/scratch/eriksen/output/bcnz/v11 /data/astro/scratch/eriksen/cache/bcnz/11 955 cosmos --ip_dask=tcp://193.109.175.131:34414
Traceback (most recent call last):
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bin/./run_bcnz.py", line 27, in <module>
    import bcnz
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/__init__.py", line 23, in <module>
    from . import bayint
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/__init__.py", line 17, in <module>
    from .bayevz_photoz import photoz_batch, photoz_dask
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/bayevz_photoz.py", line 5, in <module>
    from . import mc_genz_cython
ImportError: cannot import name 'mc_genz_cython' from partially initialized module 'bcnz.bayint' (most likely due to a circular import) (/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/__init__.py)

**Comment by marberi** [comment]
Actually also gets triggered when starting the bayesian evidence code.

(bcnz) [eriksen@tdg001 bin]$ python run_bayevz_simple.py
Traceback (most recent call last):
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bin/run_bayevz_simple.py", line 23, in <module>
    import bcnz
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/__init__.py", line 23, in <module>
    from . import bayint
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/__init__.py", line 17, in <module>
    from .bayevz_photoz import photoz_batch, photoz_dask
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/bayevz_photoz.py", line 5, in <module>
    from . import mc_genz_cython
ImportError: cannot import name 'mc_genz_cython' from partially initialized module 'bcnz.bayint' (most likely due to a circular import) (/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/__init__.py)

**Comment by marberi** [comment]
Just to note.... This problem really does not (directly) have anything TODO with the command line. It also happens with when importing BCNz in a notebook ("import bcnz").

**Comment by alexalar** [comment]
not sure why this wasn't a problem for me. I've modified the import so it happens in the innit file instead.

**Comment by marberi** [comment]
By now it returns.

(bcnz) [eriksen@tdg001 bin]$ ./run_bcnz.py /data/astro/scratch/eriksen/output/bcnz/v11 /data/astro/scratch/eriksen/cache/bcnz/11 955 cosmos
Traceback (most recent call last):
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bin/./run_bcnz.py", line 27, in <module>
    import bcnz
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/__init__.py", line 23, in <module>
    from . import bayint
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/__init__.py", line 17, in <module>
    from .bayevz_photoz import photoz_batch, photoz_dask
  File "/nfs/pic.es/user/e/eriksen/code/bcnz/bcnz/bayint/bayevz_photoz.py", line 5, in <module>
    import bcnz.bayint.mc_genz_cython as mc_genz_cython
ModuleNotFoundError: No module named 'bcnz.bayint.mc_genz_cython'

**Comment by alexalar** [comment]
Now I was able to reproduce this error. For some reason when importing bcnz at the path `/bcnz/bcnz/bin` (where I always run things) no error is raised, but from other folders then the error is raised.

**Comment by alexalar** [comment]
It seems I don't need to import the cython modules again, as I compile them in the setup file as extension modules. Now I don't get the error anymore.

**Comment by marberi** [comment]
Got this working after installing by running the setup.py file again...

By now it complains that it cannot find the "cosmolopy" module. I might have introduced you to this
package many years ago... but we should try to use "astropy", which we already need for some other
parts of the code.

(I can do this later today)

**Comment by marberi** [comment]
Hi Alex,

I installed "comolopy" to compare. When running:
cosmo = {"omega_M_0": 0.25, "omega_lambda_0": 0.75, "h": 0.7}
cosmo = cd.set_omega_k_0(cosmo)

is complains that: 
"AttributeError: module 'cosmolopy' has no attribute 'set_omega_k_0'"

**Comment by marberi** [comment]
Found the problem. Never mind.

**Comment by marberi** [comment]
Testing on 10 redshifts between z=0 and z=1.5 and the astropy code:

from astropy.cosmology import w0waCDM
cosmo = w0waCDM(H0=70, Om0=0.25, Ode0=0.75) 

the cosmolopy and astropy gives a the same distance to a relative difference of 4.723012155693251e-16.
I have updated the code to use astropy and pushed the changes.


when using
DM = 5 * np.log10(np.array(cosmo.luminosity_distance(z_DM)) * 1e5)

**Comment by marberi** [comment]
By now the BCNz2 calibration is running....

**Comment by alexalar** [comment]
Thanks a lot for updating this!
